/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   printf.c                                           :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: lubenard <lubenard@student.42.fr>          +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2019/01/23 16:40:07 by lubenard          #+#    #+#             */
/*   Updated: 2021/02/12 12:13:24 by lubenard         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include <limits.h>
#include "../includes/test_header.h"


void launch_tests_printf(void)
{
	int test1 = 1000000000;
	short int test2 = 10000;
	char test3 = 42;
	long int test4 = 4000000000;
	long long int test5 = 8000000000;
	int *test6 = &test1;
	unsigned short test7 = 100;
	unsigned long test8 = 4000000000;
	unsigned long long test9 = 8000000000;
	unsigned int test10 = 4294967295;
	char *test11 = NULL;
	char *test12 = 0x0;
	int test13 = INT_MAX;
	char *str = NULL;

	printf("VRAI PRINTF:\n");
	printf("-----Test normaux-----\n");
	printf("test printf\n");
	printk(KERN_NORMAL,"test printf\n");
	printf("\0");
	printk(KERN_NORMAL,"\0");
	printf("");
	printk(KERN_NORMAL,"");
	printf("-----Test %%c-----\n");
	printf("%c\n", 'k');
	printk(KERN_NORMAL,"%c\n", 'k');
	printf("%c\n", '\n');
	printk(KERN_NORMAL,"%c\n", '\n');
	printf("%c\n", '\0');
	printk(KERN_NORMAL,"%c\n", '\0');
	printf("test avec 0 : '%c'\n", 0);
	printk(KERN_NORMAL,"test avec 0 : '%c'\n", 0);
	printf("-----Test %%s-----\n");
	printf("%s\n", "POULOULOU");
	printk(KERN_NORMAL,"%s\n", "POULOULOU");
	printf("%s\n", "\0");
	printk(KERN_NORMAL,"%s\n", "\0");
	printf("%s", "JURE LE YA UN RETOUR LIGNE\n");
	printk(KERN_NORMAL,"%s", "JURE LE YA UN RETOUR LIGNE\n");
	printf("-----Test %%p-----\n");
	printf("%p\n", test6);
	printk(KERN_NORMAL,"%p\n", test6);
	printf("%p\n", test11);
	printk(KERN_NORMAL,"%p\n", test11);
	printf("%p\n", test12);
	printk(KERN_NORMAL,"%p\n", test12);
	printf("-----Test %%%%-----\n");
	printf("%%\n");
	printk(KERN_NORMAL,"%%\n");
	printf("-----Test %%d et %%i-----\n");
	printf("%d\n", test1);
	printk(KERN_NORMAL,"%d\n", test1);
	printf("%i\n", test1);
	printk(KERN_NORMAL,"%i\n", test1);
	printf("%d\n", test13);
	printk(KERN_NORMAL,"%d\n", test13);
	printf("%hd\n", test2);
	printk(KERN_NORMAL,"%hd\n", test2);
	printf("%hi\n", test2);
	printk(KERN_NORMAL,"%hi\n", test2);
	printf("%hhd\n", test3);
	printk(KERN_NORMAL,"%hhd\n", test3);
	printf("%hhi\n", test3);
	printk(KERN_NORMAL,"%hhi\n", test3);
	printf("%ld\n", test4);
	printk(KERN_NORMAL,"%ld\n", test4);
	printf("%li\n",test4);
	printk(KERN_NORMAL,"%li\n",test4);
	printf("%lld\n", test5);
	printk(KERN_NORMAL,"%lld\n", test5);
	printf("%lli\n", test5);
	printk(KERN_NORMAL,"%lli\n", test5);
	printf("-----Test %%o-----\n");
	printf("%o\n", 1000);
	printk(KERN_NORMAL,"%o\n", 1000);
	printf("%o\n", 0x1000);
	printk(KERN_NORMAL,"%o\n", 0x1000);
	printf("%ho\n", test7);
	printk(KERN_NORMAL,"%ho\n", test7);
	printf("%hho\n", test3);
	printk(KERN_NORMAL,"%hho\n", test3);
	printf("%lo\n", test8);
	printk(KERN_NORMAL,"%lo\n", test8);
	printf("%llo\n", test9);
	printk(KERN_NORMAL,"%llo\n", test9);
	printf("-----Test %%u-----\n");
	printf("%u\n", 1000);
	printk(KERN_NORMAL,"%u\n", 1000);
	printf("%u\n", test10);
	printk(KERN_NORMAL,"%u\n", test10);
	printf("%u\n", -1);
	printk(KERN_NORMAL,"%u\n", -1);
	printf("%u\n", -100);
	printk(KERN_NORMAL,"%u\n", -100);
	printf("%hu\n", test7);
	printk(KERN_NORMAL,"%hu\n", test7);
	printf("%hhu\n", test3);
	printk(KERN_NORMAL,"%hhu\n", test3);
	printf("%lu\n", test8);
	printk(KERN_NORMAL,"%lu\n", test8);
	printf("%llu\n", test9);
	printk(KERN_NORMAL,"%llu\n", test9);
	printf("-----Test %%x et %%X-----\n");
	printf("%x\n", 1000);
	printk(KERN_NORMAL,"%x\n", 1000);
	printf("%hx\n", test7);
	printk(KERN_NORMAL,"%hx\n", test7);
	printf("%hhx\n", test3);
	printk(KERN_NORMAL,"%hhx\n", test3);
	printf("%lx\n", test8);
	printk(KERN_NORMAL,"%lx\n", test8);
	printf("%llx\n", test9);
	printk(KERN_NORMAL,"%llx\n", test9);
	printf("%X\n", 1000);
	printk(KERN_NORMAL,"%X\n", 1000);
	printf("%hX\n", test7);
	printk(KERN_NORMAL,"%hX\n", test7);
	printf("%hhX\n", test3);
	printk(KERN_NORMAL,"%hhX\n", test3);
	printf("%lX\n", test8);
	printk(KERN_NORMAL,"%lX\n", test8);
	printf("%llX\n", test9);
	printk(KERN_NORMAL,"%llX\n", test9);
	printf("-----Test Minwidth-----\n");
	printf("Pourcent c: '%10c'\n", 'o');
	printk(KERN_NORMAL,"Pourcent c: '%10c'\n", 'o');
	printf("Pourcent c: '%-10c'\n", 'o');
	printk(KERN_NORMAL,"Pourcent c: '%-10c'\n", 'o');
	printf("Pourcent s: '%10s'\n", "hihihi");
	printk(KERN_NORMAL,"Pourcent s: '%10s'\n", "hihihi");
	printf("Pourcent s: '%-10s'\n", "hihihi");
	printk(KERN_NORMAL,"Pourcent s: '%-10s'\n", "hihihi");
	printf("Pourcent s: '%10s'\n", "hohohohohohohoho");
	printk(KERN_NORMAL,"Pourcent s: '%10s'\n", "hohohohohohohoho");
	printf("Pourcent s: '%-10s'\n", "hohohohohohohoho");
	printk(KERN_NORMAL,"Pourcent s: '%-10s'\n", "hohohohohohohoho");
	printf("Pourcent p: '%20p'\n", test6);
	printk(KERN_NORMAL,"Pourcent p: '%20p'\n", test6);
	printf("Pourcent p: '%-20p'\n", test6);
	printk(KERN_NORMAL,"Pourcent p: '%-20p'\n", test6);
	printf("Pourcent di: '%10d'\n", 42);
	printk(KERN_NORMAL,"Pourcent di: '%10d'\n", 42);
	printf("Pourcent di: '%-10d'\n", 42);
	printk(KERN_NORMAL,"Pourcent di: '%-10d'\n", 42);
	printf("Pourcent di: '%10d'\n", -1000);
	printk(KERN_NORMAL,"Pourcent di: '%10d'\n", -1000);
	printf("Pourcent di: '%-10d'\n", -1000);
	printk(KERN_NORMAL,"Pourcent di: '%-10d'\n", -1000);
	printf("Pourcent o: '%10o' \n", 1000);
	printk(KERN_NORMAL,"Pourcent o: '%10o' \n", 1000);
	printf("Pourcent o: '%-10o'\n", 1000);
	printk(KERN_NORMAL,"Pourcent o: '%-10o'\n", 1000);
	printf("Pourcent u: '%10u'\n", 100);
	printk(KERN_NORMAL,"Pourcent u: '%10u'\n", 100);
	printf("Pourcent u: '%-10u'\n", 100);
	printk(KERN_NORMAL,"Pourcent u: '%-10u'\n", 100);
	printf("Pourcent x: '%10x'\n", 1000);
	printk(KERN_NORMAL,"Pourcent x: '%10x'\n", 1000);
	printf("Pourcent X: '%10X'\n", 1000);
	printk(KERN_NORMAL,"Pourcent X: '%10X'\n", 1000);
	printf("Pourcent X: '%-10X'\n", 1000);
	printk(KERN_NORMAL,"Pourcent X: '%-10X'\n", 1000);
	printf("Pourcent pourcent : '%10%'\n");
	printk(KERN_NORMAL,"Pourcent pourcent : '%10%'\n");
	printf("Pourcent pourcent : '%-10%'\n");
	printk(KERN_NORMAL,"Pourcent pourcent : '%-10%'\n");
	printf("-----Test precision-----\n");
	printf("Pourcent c: '%.10c'\n", 'o');
	printk(KERN_NORMAL,"Pourcent c: '%.10c'\n", 'o');
	printf("Pourcent s: '%.10s'\n", "hohohohohohohoho");
	printk(KERN_NORMAL,"Pourcent s: '%.10s'\n", "hohohohohohohoho");
	printf("Pourcent p: '%.20p'\n", test6);
	printk(KERN_NORMAL,"Pourcent p: '%.20p'\n", test6);
	printf("Pourcent d: '%.10d'\n", 42);
	printk(KERN_NORMAL,"Pourcent d: '%.10d'\n", 42);
	printf("Pourcent o: '%.10o' \n", 1000);
	printk(KERN_NORMAL,"Pourcent o: '%.10o' \n", 1000);
	printf("Pourcent u: '%.10u'\n", 100);
	printk(KERN_NORMAL,"Pourcent u: '%.10u'\n", 100);
	printf("Pourcent x: '%.10x'\n", 1000);
	printk(KERN_NORMAL,"Pourcent x: '%.10x'\n", 1000);
	printf("Pourcent X: '%.10X'\n", 1000);
	printk(KERN_NORMAL,"Pourcent X: '%.10X'\n", 1000);
	printf("Pourcent pourcent : '%.10%'\n");
	printk(KERN_NORMAL,"Pourcent pourcent : '%.10%'\n");
	printf("Pourcent D: '%5.d' '%5.0d'\n", 0, 0);
	printk(KERN_NORMAL,"Pourcent D: '%5.d' '%5.0d'\n", 0, 0);
	printf("-----Test +- #0-----\n");
	printf("espace positif '% d'\n", 1000);
	printk(KERN_NORMAL,"espace positif '% d'\n", 1000);
	printf("espace negatif '% d'\n", -1000);
	printk(KERN_NORMAL,"espace negatif '% d'\n", -1000);
	printf("plus positif '%+d'\n", 1000);
	printk(KERN_NORMAL,"plus positif '%+d'\n", 1000);
	printf("plus negatif '%+d'\n", -1000);
	printk(KERN_NORMAL,"plus negatif '%+d'\n", -1000);
	printf("moins positif '%-10d'\n", 1000);
	printk(KERN_NORMAL,"moins positif '%-10d'\n", 1000);
	printf("moins negatif '%-10d'\n", -1000);
	printk(KERN_NORMAL,"moins negatif '%-10d'\n", -1000);
	printf("zero positif '%010d'\n", 1000);
	printk(KERN_NORMAL,"zero positif '%010d'\n", 1000);
	printf("zero negatif '%010d'\n", -1000);
	printk(KERN_NORMAL,"zero negatif '%010d'\n", -1000);
	printf("zero negatif '%010.6d'\n", -1000);
	printk(KERN_NORMAL,"zero negatif '%10.6d'\n", -1000);
	printf("zero + prec '%-010d'\n", -1000);
	printk(KERN_NORMAL,"zero + prec '%-010d'\n", -1000);
	printf("----------------------------------\n");
	printf("vrai printf avec +d '%+d'\n", -42);
	printk(KERN_NORMAL,"mien printf avec +d '%+d'\n", -42);
	printf("vrai printf avec + d '%+ d'\n", -42);
	printk(KERN_NORMAL,"mien printf avec + d '%+ d'\n", -42);
	printf("vrai printf avec +  d '%+  d'\n", -42);
	printk(KERN_NORMAL,"mien printf avec +  d '%+  d'\n", -42);
	printf("vrai printf avec #0x '%#0x'\n", 0);
	printk(KERN_NORMAL,"mien printf avec #0x '%#0x'\n", 0);
	printf("vrai printf avec #x '%#x'\n", 42);
	printk(KERN_NORMAL,"mien printf avec #x '%#x'\n", 42);
	printf("vrai printf avec #x '%#8x'\n", 42);
	printk(KERN_NORMAL,"mien printf avec #x '%#8x'\n", 42);
	printf("vrai printf avec 2x '%2x'\n", 542);
	printk(KERN_NORMAL,"mien printf avec 2x '%2x'\n", 542);
	printf("vrai printf avec #6o '%2o'\n", 542);
	printk(KERN_NORMAL,"mien printf avec #6o '%2o'\n", 542);
	printf("vrai printf avec lu '%lu'\n", -42);
	printk(KERN_NORMAL,"mien printf avec lu '%lu'\n", -42);
	printf("vrai printf avec -#08.15x '%#-08.15x'\n", 42);
	printk(KERN_NORMAL,"mien printf avec -#08.15x '%#-08.15x'\n", 42);
	printf("vrai printf avec #-08x '%#-08x'\n", 42);
	printk(KERN_NORMAL,"mien printf avec #-08x '%#-08x'\n", 42);
	printf("@moulitest: '%#.x' '%#.0x'\n", 0, 0);
	printk(KERN_NORMAL,"@moulitest: '%#.x' '%#.0x'\n", 0, 0);
	printf("vrai printf avec lu '%lu'\n", -42);
	printk(KERN_NORMAL,"mien printf avec lu '%lu'\n", -42);
	printf("vrai printf avec .0o '%.0o'\n", 0);
	printk(KERN_NORMAL,"mien printf avec .0o '%.0o'\n", 0);
	printf("vrai printf avec lld '%lld'\n", (long long)LLONG_MIN);
	printk(KERN_NORMAL,"mien printf avec lld '%lld'\n", (long long)LLONG_MIN);
	printf("vrai printf avec #6o '%#6o'\n", 2500);
	printk(KERN_NORMAL,"mien printf avec #6o '%#6o'\n", 2500);
	printf("vrai printf avec -#6o '%-#6o'\n", 2500);
	printk(KERN_NORMAL,"mien printf avec -#6o '%-#6o'\n", 2500);
	printf("vrai printf avec -.2s '%-.2s'\n", "");
	printk(KERN_NORMAL,"mien printf avec -.2s '%-.2s'\n", "");
	printf("vrai printf avec ho '%ho'\n", (short)-127);
    printk(KERN_NORMAL,"mien printf avec ho '%ho'\n", (short)-127);
    printf("vrai avec '%#8x'\n", 50);
    printk(KERN_NORMAL,"mien avec '%#8x'\n", 50);
    printf("%lu\n", (long)-42);
	printk(KERN_NORMAL,"%lu\n", (long)-42);
	printf("------------Test Lolo----------------------");
	printf("------1------\n");
	printf("|%s|\n", "this is a string");
	printk(KERN_NORMAL,"|%s|\n", "this is a string");
	printf("------2-------\n");
	printf("|%s|\n", NULL);
	printk(KERN_NORMAL,"|%s|\n", NULL);
	printf("------3-------\n");
	printf("|%s|\n", "lol");
	printk(KERN_NORMAL,"|%s|\n", "lol");
	printf("------4-------\n");
	printf("|%llx|\n", (long long)10);
	printk(KERN_NORMAL,"|%llx|\n", (long long)10);
	printf("------5-------\n");
	printf("|%-20s| is a string\n", "this");
	printk(KERN_NORMAL,"|%-20s| is a string\n", "this");
	printf("------6-------\n");
	printf("|%-2s| is a string\n", "this");
	printk(KERN_NORMAL,"|%-2s| is a string\n", "this");
	printf("------7-------\n");
	printf("|%-.2s| is a string\n", "this");
	printk(KERN_NORMAL,"|%-.2s| is a string\n", "this");
	printf("------8-------\n");
	printf("|%-5.2s| is a string\n", "this");
	printk(KERN_NORMAL,"|%-5.2s| is a string\n", "this");
	printf("------9-------\n");
	printf("|%-7.7s| is a string\n", "this");
	printk(KERN_NORMAL,"|%-7.7s| is a string\n", "this");
	printf("-----10-------\n");
	printf("|%-5.2s| is a string\n", "");
	printk(KERN_NORMAL,"|%-5.2s| is a string\n", "");
	printf("-----11-------\n");
	printf("|%-1.0d|\n", -18);
	printk(KERN_NORMAL,"|%-1.0d|\n", -18);
	printf("-----12-------\n");
	printf("|%#10o|\n", 524);
	printk(KERN_NORMAL,"|%#10o|\n", 524);
	printf("-----13-------\n");
	printf("|%08x|\n", 42);
	printk(KERN_NORMAL,"|%08x|\n", 42);
	printf("-----14-------\n");
	printf("|%10.08x|\n", 42);
	printk(KERN_NORMAL,"|%10.08x|\n", 42);
	printf("-----15-------\n");
	printf("|%.8x|\n", 42);
	printk(KERN_NORMAL,"|%.8x|\n", 42);
	printf("-----16-------\n");
	printf("|%-5.2s| is a string\n", "");
	printk(KERN_NORMAL,"|%-5.2s| is a string\n", "");
	printf("-----17-------\n");
	printf("|%+d|\n", -42);
	printk(KERN_NORMAL,"|%+d|\n", -42);
	printf("-----18-------\n");
	printf("|% d|\n", -42);
	printk(KERN_NORMAL,"|% d|\n", -42);
	printf("-----19-------\n");
	printf("|%+5d|\n", 42);
	printk(KERN_NORMAL,"|%+5d|\n", 42);
	printf("-----20-------\n");
	printf("|%+4.5d|\n", 42);
	printk(KERN_NORMAL,"|%+4.5d|\n", 42);
	printf("-----21-------\n");
	printf("|%+.5d|\n", 42);
	printk(KERN_NORMAL,"|%+.5d|\n", 42);
	printf("-----22-------\n");
	printf("|%05d|\n", -42);
	printk(KERN_NORMAL,"|%05d|\n", -42);
	printf("-----23-------\n");
	printf("|%03.2d|\n", -1);
	printk(KERN_NORMAL,"|%03.2d|\n", -1);
	printf("-----24-------\n");
	printf("|%#o|\n", 42);
	printk(KERN_NORMAL,"|%#o|\n", 42);
	printf("-----25-------\n");
	printf("|%#5x|\n", 42);
	printk(KERN_NORMAL,"|%#5x|\n", 42);
	printf("-----26-------\n");
	printf("|%#05x|\n", 42);
	printk(KERN_NORMAL,"|%#05x|\n", 42);
	printf("-----27-------\n");
	printf("|%#.05x|\n", 42);
	printk(KERN_NORMAL,"|%#.05x|\n", 42);
	printf("-----28-------\n");
	printf("|%#08o|\n", 42);
	printk(KERN_NORMAL,"|%#08o|\n", 42);
	printf("-----29-------\n");
	printf("|%+05d|\n", 42);
	printk(KERN_NORMAL,"|%+05d|\n", 42);
	printf("-----30-------\n");
	printf("|%0+5d|\n", -42);
	printk(KERN_NORMAL,"|%0+5d|\n", -42);
	printf("-----31-------\n");
	printf("|%0+5d|\n", 42);
	printk(KERN_NORMAL,"|%0+5d|\n", 42);
	printf("-----32-------\n");
	printf("|%#10.05x|\n", 42);
	printk(KERN_NORMAL,"|%#10.05x|\n", 42);
	printf("-----33-------\n");
	printf("|%-20.8o|\n", -42);
	printk(KERN_NORMAL,"|%-20.8o|\n", -42);
	printf("-----34-------\n");
	printf("|%-20.15o|\n", -42);
	printk(KERN_NORMAL,"|%-20.15o|\n", -42);
	printf("-----35-------\n");
	printf("|%-3.6o|\n", -17);
	printk(KERN_NORMAL,"|%-3.6o|\n", -17);
	printf("-----36-------\n");
	printf("|%.0s|\n", "salutttt");
	printk(KERN_NORMAL,"|%.0s|\n", "salutttt");
	printf("-----37-------\n");
	printf("|% %|\n");
	printk(KERN_NORMAL,"|% %|\n");
	printf("-----38-------\n");
	printf("%% |%2.11u|\n", 18);
	printk(KERN_NORMAL,"%% |%2.11u|\n", 18);
	printf("-----39-------\n");
	printf("|%07.5d|,|%d|\n",150789, 17);
	printk(KERN_NORMAL,"|%07.5d|,|%d|\n",150789, 17);
	printf("-----40-------\n");
	printf("|%00.05d| \n", 7);
	printk(KERN_NORMAL,"|%00.05d| \n", 7);
	printf("-----41-------\n");
	printf("|%05.2d|\n", 7);
	printk(KERN_NORMAL,"|%05.2d|\n", 7);
	printf("-----42-------\n");
	printf("|%5%|\n");
	printk(KERN_NORMAL,"|%5%|\n");
	printf("-----43-------\n");
	printf("|%.5%|\n");
	printk(KERN_NORMAL,"|%.5%|\n");
	printf("-----44-------\n");
	printf("|%-.5%|\n");
	printk(KERN_NORMAL,"|%-.5%|\n");
	printf("-----45-------\n");
	printf("|%8.5%|\n");
	printk(KERN_NORMAL,"|%8.5%|\n");
	printf("-----46-------\n");
	printf("|%+8.5%|\n");
	printk(KERN_NORMAL,"|%+8.5%|\n");
	printf("-----47-------\n");
	printf("|%-5%|\n");
	printk(KERN_NORMAL,"|%-5%|\n");
	printf("-----48-------\n");
	printf("|%-8.5%|\n");
	printk(KERN_NORMAL,"|%-8.5%|\n");
	printf("-----49-------\n");
	printf("|%+-8.5%|\n");
	printk(KERN_NORMAL,"|%+-8.5%|\n");
	printf("-----50-------\n");
	printf("|%-8.5%|\n");
	printk(KERN_NORMAL,"|%-8.5%|\n");
	printf("-----51-------\n");
	printf("|%5.2s| is a string\n", "this");
	printk(KERN_NORMAL,"|%5.2s| is a string\n", "this");
	printf("-----52-------\n");
	printf("|%12s| is a string\n", "this");
	printk(KERN_NORMAL,"|%12s| is a string\n", "this");
	printf("-----53-------\n");
	printf("|%#.x| |%#.0x|\n", 0, 0);
	printk(KERN_NORMAL,"|%#.x| |%#.0x|\n", 0, 0);
	printf("-----54-------\n");
	printf("|%5.x| |%5.0x|\n", 0, 0);
	printk(KERN_NORMAL,"|%5.x| |%5.0x|\n", 0, 0);
	printf("-----55-------\n");
	printf("|%.x| |%.0x|\n", 0, 0);
	printk(KERN_NORMAL,"|%.x| |%.0x|\n", 0, 0);
	printf("|%.0s|\n",str);
	printk(KERN_NORMAL,"|%.0s|\n\n",str);
	printf("|%55.0s|\n",str);
	printk(KERN_NORMAL,"|%55.0s|\n\n",str);
	printf("|%-55.10s|\n",str);
	printk(KERN_NORMAL,"|%-55.10s|\n\n",str);
	printf("|%55.10s|\n",str);
	printk(KERN_NORMAL,"|%55.10s|\n\n",str);
	printf("|%#.8x|\n",42424242);
	printk(KERN_NORMAL,"|%#.8x|\n\n",42424242);
	printf("|%#12.2o|\n", 0);					
	printk(KERN_NORMAL,"|%#12.2o|\n", 0);
	printf("|%#10.8o|\n", 424242);
	printk(KERN_NORMAL,"|%#10.8o|\n", 424242);
	printf("Vrai PRINTF : |%10c|\n", 0);
	printk(KERN_NORMAL,"Mien PRINTF : |%10c|\n\n", 0);
	printf("Vrai PRINTF : |%.0c|\n", 0);
	printk(KERN_NORMAL,"Mien PRINTF : |%.0c|\n\n", 0);
	printf("-----------------Test Kevin------------------------\n");
	printk(KERN_NORMAL,"--------------------%%d-et-%%i--------------------\n");
	printf("01) Vrai PRINTF : |%d|\n", 42);
	printk(KERN_NORMAL,"01) Mon PRINTF  : |%d|\n", 42);
	printf("02) Vrai PRINTF : |%i|\n", 42);
	printk(KERN_NORMAL,"02) Mon PRINTF  : |%i|\n", 42);
	printf("03) Vrai PRINTF : |%+d|\n", 42);
	printk(KERN_NORMAL,"03) Mon PRINTF  : |%+d|\n", 42);
	printf("04) Vrai PRINTF : |%-d|\n", 42);
	printk(KERN_NORMAL,"04) Mon PRINTF  : |%-d|\n", 42);
	printf("05) Vrai PRINTF : |%10d|\n", 100);
	printk(KERN_NORMAL,"05) Mon PRINTF  : |%10d|\n", 100);
	printf("06) Vrai PRINTF : |%-10d|\n", 64);
	printk(KERN_NORMAL,"06) Mon PRINTF  : |%-10d|\n", 64);
	printf("07) Vrai PRINTF : |%.10d|\n", 100);
	printk(KERN_NORMAL,"07) Mon PRINTF  : |%.10d|\n", 100);
	printf("08) Vrai PRINTF : |%10.5d|\n", 100);
	printk(KERN_NORMAL,"08) Mon PRINTF  : |%10.5d|\n", 100);
	printf("09) Vrai PRINTF : |%5.10d|\n", 64);
	printk(KERN_NORMAL,"09) Mon PRINTF  : |%5.10d|\n", 64);
	printf("10) Vrai PRINTF : |%1.1d|\n", 16);
	printk(KERN_NORMAL,"10) Mon PRINTF  : |%1.1d|\n", 16);
	printf("11) Vrai PRINTF : |%+10d|\n", 50);
	printk(KERN_NORMAL,"11) Mon PRINTF  : |%+10d|\n", 50);
	printf("12) Vrai PRINTF : |%+2d|\n", 50);
	printk(KERN_NORMAL,"12) Mon PRINTF  : |%+2d|\n", 50);
	printf("13) Vrai PRINTF : |%+.10d|\n", 50);
	printk(KERN_NORMAL,"13) Mon PRINTF  : |%+.10d|\n", 50);
	printf("14) Vrai PRINTF : |%+.2d|\n", 50);
	printk(KERN_NORMAL,"14) Mon PRINTF  : |%+.2d|\n", 50);
	printf("15) Vrai PRINTF : |%          d|\n", 1);
	printk(KERN_NORMAL,"15) Mon PRINTF  : |%          d|\n", 1);
	printf("16) Vrai PRINTF : |% -d|\n", 1);
	printk(KERN_NORMAL,"16) Mon PRINTF  : |% -d|\n", 1);
	printf("17) Vrai PRINTF : |%-+d|\n", 32);
	printk(KERN_NORMAL,"17) Mon PRINTF  : |%-+d|\n", 32);
	printf("18) Vrai PRINTF : |%+-d|\n", 32);
	printk(KERN_NORMAL,"18) Mon PRINTF  : |%+-d|\n", 32);
	printf("19) Vrai PRINTF : |%-+10d|\n", 42);
	printk(KERN_NORMAL,"19) Mon PRINTF  : |%-+10d|\n", 42);
	printf("20) Vrai PRINTF : |%-+.10d|\n", 42);
	printk(KERN_NORMAL,"20) Mon PRINTF  : |%-+.10d|\n", 42);
	printf("21) Vrai PRINTF : |%d|\n", -42);
	printk(KERN_NORMAL,"21) Mon PRINTF  : |%d|\n", -42);
	printf("22) Vrai PRINTF : |%10d|\n", -42);
	printk(KERN_NORMAL,"22) Mon PRINTF  : |%10d|\n", -42);
	printf("23) Vrai PRINTF : |%.10d|\n", -42);
	printk(KERN_NORMAL,"23) Mon PRINTF  : |%.10d|\n", -42);
	printf("24) Vrai PRINTF : |%+d|\n", -10);
	printk(KERN_NORMAL,"24) Mon PRINTF  : |%+d|\n", -10);
	printf("25) Vrai PRINTF : |%10.5d|\n", -16);
	printk(KERN_NORMAL,"25) Mon PRINTF  : |%10.5d|\n", -16);
	printf("26) Vrai PRINTF : |%5.10d|\n", -16);
	printk(KERN_NORMAL,"26) Mon PRINTF  : |%5.10d|\n", -16);
	printf("27) Vrai PRINTF : |%1.1d|\n", -20);
	printk(KERN_NORMAL,"27) Mon PRINTF  : |%1.1d|\n", -20);
	printf("28) Vrai PRINTF : |%-10d|\n", -50);
	printk(KERN_NORMAL,"29) Mon PRINTF  : |%-10d|\n", -50);
	printf("30) Vrai PRINTF : |%++++++++++d|\n", 69);
	printk(KERN_NORMAL,"30) Mon PRINTF  : |%++++++++++d|\n", 69);
	printf("31) Vrai PRINTF : |%+10d|\n", -64);
	printk(KERN_NORMAL,"31) Mon PRINTF  : |%+10d|\n", -64);
	printf("32) Vrai PRINTF : |%+.10d|\n", -64);
	printk(KERN_NORMAL,"32) Mon PRINTF  : |%+.10d|\n", -64);
	printf("33) Vrai PRINTF : |%2d|\n", -20);
	printk(KERN_NORMAL,"33) Mon PRINTF  : |%2d|\n", -20);
	printf("34) Vrai PRINTF : |%.2d|\n", -20);
	printk(KERN_NORMAL,"34) Mon PRINTF  : |%.2d|\n", -20);
	printf("35) Vrai PRINTF : |%2d|\n", -1);
	printk(KERN_NORMAL,"35) Mon PRINTF  : |%2d|\n", -1);
	printf("36) Vrai PRINTF : |%.2d|\n", -1);
	printk(KERN_NORMAL,"36) Mon PRINTF  : |%.2d|\n", -1);
	printf("37) Vrai PRINTF : |%-10d|\n", -80);
	printk(KERN_NORMAL,"37) Mon PRINTF  : |%-10d|\n", -80);
	printf("38) Vrai PRINTF : |%-.10d|\n", -80);
	printk(KERN_NORMAL,"38) Mon PRINTF  : |%-.10d|\n", -80);
	printf("39) Vrai PRINTF : |%06d|\n", 35);
	printk(KERN_NORMAL,"39) Mon PRINTF  : |%06d|\n", 35);
	printf("40) Vrai PRINTF : |%06d|\n", -35);
	printk(KERN_NORMAL,"40) Mon PRINTF  : |%06d|\n", -35);
	printf("41) Vrai PRINTF : |%-+10d|\n", -40);
	printk(KERN_NORMAL,"41) Mon PRINTF  : |%-+10d|\n", -40);
	printf("42) Vrai PRINTF : |%+-10d|\n", -40);
	printk(KERN_NORMAL,"42) Mon PRINTF  : |%+-10d|\n", -40);
	printf("43) Vrai PRINTF : |%05.3d|\n", 5);
	printk(KERN_NORMAL,"43) Mon PRINTF  : |%05.3d|\n", 5);
	printf("44) Vrai PRINTF : |%03.5d|\n", 5);
	printk(KERN_NORMAL,"44) Vrai PRINTF : |%03.5d|\n", 5);
	printf("45) Vrai PRINTF : |%05.3d|\n", -5);
	printk(KERN_NORMAL,"45) Mon PRINTF  : |%05.3d|\n", -5);
	printf("46) Vrai PRINTF : |%03.5d|\n", -5);
	printk(KERN_NORMAL,"46) Mon PRINTF  : |%03.5d|\n", -5);
	printf("47) Vrai PRINTF : |%d| |%d|\n", INT_MAX, INT_MIN);
	printk(KERN_NORMAL,"47) Mon PRINTF  : |%d| |%d|\n", INT_MAX, INT_MIN);
	printf("48) Vrai PRINTF : |%d| |%d|\n", INT_MAX + 1, INT_MIN - 1);
	printk(KERN_NORMAL,"48) Vrai PRINTF : |%d| |%d|\n", INT_MAX + 1, INT_MIN - 1);
	printf("49) Vrai PRINTF : |%.d|\n", 0);
	printk(KERN_NORMAL,"49) Mon PRINTF  : |%.d|\n", 0);
	printf("50) Vrai PRINTF : |%.d|\n", 100);
	printk(KERN_NORMAL,"50) Mon PRINTF  : |%.d|\n", 100);
	printk(KERN_NORMAL,"--------------------%%o--------------------\n");
	printf("01) Vrai PRINTF : |%o|\n", 34);
	printk(KERN_NORMAL,"01) Mon PRINTF  : |%o|\n", 34);
	printf("02) Vrai PRINTF : |%o|\n", -34);
	printk(KERN_NORMAL,"02) Mon PRINTF  : |%o|\n", -34);
	printf("03) Vrai PRINTF : |%-o|\n", 50);
	printk(KERN_NORMAL,"03) Mon PRINTF  : |%-o|\n", 50);
	printf("04) Vrai PRINTF : |%10o|\n", 90);
	printk(KERN_NORMAL,"04) Mon PRINTF  : |%10o|\n", 90);
	printf("05) Vrai PRINTF : |%.10o|\n", 90);
	printk(KERN_NORMAL,"05) Mon PRINTF  : |%.10o|\n", 90);
	printf("06) Vrai PRINTF : |%15o|\n", -100);
	printk(KERN_NORMAL,"06) Mon PRINTF  : |%15o|\n", -100);
	printf("07) Vrai PRINTF : |%.15o|\n", -100);
	printk(KERN_NORMAL,"07) Mon PRINTF  : |%.15o|\n", -100);
	printf("08) Vrai PRINTF : |%10.5o|\n", 52);
	printk(KERN_NORMAL,"08) Mon PRINTF  : |%10.5o|\n", 52);
	printf("09) Vrai PRINTF : |%5.10o|\n", 52);
	printk(KERN_NORMAL,"09) Mon PRINTF  : |%5.10o|\n", 52);
	printf("10) Vrai PRINTF : |%20.15o|\n", -100000);
	printk(KERN_NORMAL,"10) Mon PRINTF  : |%20.15o|\n", -100000);
	printf("11) Vrai PRINTF : |%15.20o|\n", -100000);
	printk(KERN_NORMAL,"11) Mon PRINTF  : |%15.20o|\n", -100000);
	printf("12) Vrai PRINTF : |%-10o|\n", 144);
	printk(KERN_NORMAL,"12) Mon PRINTF  : |%-10o|\n", 144);
	printf("13) Vrai PRINTF : |%-.10o|\n", 144);
	printk(KERN_NORMAL,"13) Mon PRINTF  : |%-.10o|\n", 144);
	printf("14) Vrai PRINTF : |%-20o|\n", -20000000);
	printk(KERN_NORMAL,"14) Mon PRINTF  : |%-20o|\n", -20000000);
	printf("15) Vrai PRINTF : |%08o|\n", 64);
	printk(KERN_NORMAL,"15) Mon PRINTF  : |%08o|\n", 64);
	printf("16) Vrai PRINTF : |%03.4o|\n", 10);
	printk(KERN_NORMAL,"16) Mon PRINTF  : |%03.4o|\n", 10);
	printf("17) Vrai PRINTF : |%#o|\n", 34);
	printk(KERN_NORMAL,"17) Mon PRINTF  : |%#o|\n", 34);
	printf("18) Vrai PRINTF : |%#.5o|\n", 34);
	printk(KERN_NORMAL,"18) Mon PRINTF  : |%#.5o|\n", 34);
	printf("19) Vrai PRINTF : |%#5o|\n", 86);
	printk(KERN_NORMAL,"19) Mon PRINTF  : |%#5o|\n", 86);
	printf("20) Vrai PRINTF : |%#10.5o|\n", 70);
	printk(KERN_NORMAL,"20) Mon PRINTF  : |%#10.5o|\n", 70);
	printf("21) Vrai PRINTF : |%#o|\n", 0);
	printk(KERN_NORMAL,"21) Vrai PRINTF : |%#o|\n", 0);
	printf("22) Vrai PRINTF : |%#.o|\n", 0);
	printk(KERN_NORMAL,"22) Mon PRINTF  : |%#.o|\n", 0);
	printf("23) Vrai PRINTF : |%.o|\n", 0);
	printk(KERN_NORMAL,"23) Mon PRINTF  : |%.o|\n", 0);
	printf("24) Vrai PRINTF : |%.o|\n", 88);
	printk(KERN_NORMAL,"24) Mon PRINTF  : |%.o|\n", 88);
	printf("25) Vrai PRINTF : |%#.o|\n", 88);
	printk(KERN_NORMAL,"25) Mon PRINTF  : |%#.o|\n", 88);
	printf("26) Vrai PRINTF : |%o|\n", UINT_MAX);
	printk(KERN_NORMAL,"26) Mon PRINTF  : |%o|\n", UINT_MAX);
	printf("27) Vrai PRINTF : |%#o|\n", UINT_MAX);
	printk(KERN_NORMAL,"27) Mon PRINTF  : |%#o|\n", UINT_MAX);
	printk(KERN_NORMAL,"--------------------%%x--------------------\n");
	printf("01) Vrai PRINTF : |%x|\n", 34);
	printk(KERN_NORMAL,"01) Mon PRINTF  : |%x|\n", 34);
	printf("02) Vrai PRINTF : |%x|\n", -34);
	printk(KERN_NORMAL,"02) Mon PRINTF  : |%x|\n", -34);
	printf("03) Vrai PRINTF : |%-x|\n", 50);
	printk(KERN_NORMAL,"03) Mon PRINTF  : |%-x|\n", 50);
	printf("04) Vrai PRINTF : |%10x|\n", 90);
	printk(KERN_NORMAL,"04) Mon PRINTF  : |%10x|\n", 90);
	printf("05) Vrai PRINTF : |%.10x|\n", 90);
	printk(KERN_NORMAL,"05) Mon PRINTF  : |%.10x|\n", 90);
	printf("06) Vrai PRINTF : |%15x|\n", -100);
	printk(KERN_NORMAL,"06) Mon PRINTF  : |%15x|\n", -100);
	printf("07) Vrai PRINTF : |%.15x|\n", -100);
	printk(KERN_NORMAL,"07) Mon PRINTF  : |%.15x|\n", -100);
	printf("08) Vrai PRINTF : |%10.5x|\n", 52);
	printk(KERN_NORMAL,"08) Mon PRINTF  : |%10.5x|\n", 52);
	printf("09) Vrai PRINTF : |%5.10x|\n", 52);
	printk(KERN_NORMAL,"09) Mon PRINTF  : |%5.10x|\n", 52);
	printf("10) Vrai PRINTF : |%20.15x|\n", -100000);
	printk(KERN_NORMAL,"10) Mon PRINTF  : |%20.15x|\n", -100000);
	printf("11) Vrai PRINTF : |%15.20x|\n", -100000);
	printk(KERN_NORMAL,"11) Mon PRINTF  : |%15.20x|\n", -100000);
	printf("12) Vrai PRINTF : |%-10x|\n", 144);
	printk(KERN_NORMAL,"12) Mon PRINTF  : |%-10x|\n", 144);
	printf("13) Vrai PRINTF : |%-.10x|\n", 144);
	printk(KERN_NORMAL,"13) Mon PRINTF  : |%-.10x|\n", 144);
	printf("14) Vrai PRINTF : |%-20x|\n", -20000000);
	printk(KERN_NORMAL,"14) Mon PRINTF  : |%-20x|\n", -20000000);
	printf("15) Vrai PRINTF : |%08x|\n", 64);
	printk(KERN_NORMAL,"15) Mon PRINTF  : |%08x|\n", 64);
	printf("16) Vrai PRINTF : |%03.4x|\n", 10);
	printk(KERN_NORMAL,"16) Mon PRINTF  : |%03.4x|\n", 10);
	printf("17) Vrai PRINTF : |%#x|\n", 34);
	printk(KERN_NORMAL,"17) Mon PRINTF  : |%#x|\n", 34);
	printf("18) Vrai PRINTF : |%#.5x|\n", 34);
	printk(KERN_NORMAL,"18) Mon PRINTF  : |%#.5x|\n", 34);
	printf("19) Vrai PRINTF : |%#5x|\n", 86);
	printk(KERN_NORMAL,"19) Mon PRINTF  : |%#5x|\n", 86);
	printf("20) Vrai PRINTF : |%#10.5x|\n", 70);
	printk(KERN_NORMAL,"20) Mon PRINTF  : |%#10.5x|\n", 70);
	printf("21) Vrai PRINTF : |%#x|\n", 0);
	printk(KERN_NORMAL,"21) Vrai PRINTF : |%#x|\n", 0);
	printf("22) Vrai PRINTF : |%#.x|\n", 0);
	printk(KERN_NORMAL,"22) Mon PRINTF  : |%#.x|\n", 0);
	printf("23) Vrai PRINTF : |%.x|\n", 0);
	printk(KERN_NORMAL,"23) Mon PRINTF  : |%.x|\n", 0);
	printf("24) Vrai PRINTF : |%.x|\n", 88);
	printk(KERN_NORMAL,"24) Mon PRINTF  : |%.x|\n", 88);
	printf("25) Vrai PRINTF : |%#.x|\n", 88);
	printk(KERN_NORMAL,"25) Mon PRINTF  : |%#.x|\n", 88);
	printf("26) Vrai PRINTF : |%x|\n", UINT_MAX);
	printk(KERN_NORMAL,"26) Mon PRINT   : |%x|\n", UINT_MAX);
	printf("27) Vrai PRINTF : |%#x|\n", UINT_MAX);
	printk(KERN_NORMAL,"27) Mon PRINTF  : |%#x|\n", UINT_MAX);
	printk(KERN_NORMAL,"--------------------%%X--------------------\n");
	printf("01) Vrai PRINTF : |%X|\n", 34);
	printk(KERN_NORMAL,"01) Mon PRINTF  : |%X|\n", 34);
	printf("02) Vrai PRINTF : |%X|\n", -34);
	printk(KERN_NORMAL,"02) Mon PRINTF  : |%X|\n", -34);
	printf("03) Vrai PRINTF : |%-X|\n", 50);
	printk(KERN_NORMAL,"03) Mon PRINTF  : |%-X|\n", 50);
	printf("04) Vrai PRINTF : |%10X|\n", 90);
	printk(KERN_NORMAL,"04) Mon PRINTF  : |%10X|\n", 90);
	printf("05) Vrai PRINTF : |%.10X|\n", 90);
	printk(KERN_NORMAL,"05) Mon PRINTF  : |%.10X|\n", 90);
	printf("06) Vrai PRINTF : |%15X|\n", -100);
	printk(KERN_NORMAL,"06) Mon PRINTF  : |%15X|\n", -100);
	printf("07) Vrai PRINTF : |%.15X|\n", -100);
	printk(KERN_NORMAL,"07) Mon PRINTF  : |%.15X|\n", -100);
	printf("08) Vrai PRINTF : |%10.5X|\n", 52);
	printk(KERN_NORMAL,"08) Mon PRINTF  : |%10.5X|\n", 52);
	printf("09) Vrai PRINTF : |%5.10X|\n", 52);
	printk(KERN_NORMAL,"09) Mon PRINTF  : |%5.10X|\n", 52);
	printf("10) Vrai PRINTF : |%20.15X|\n", -100000);
	printk(KERN_NORMAL,"10) Mon PRINTF  : |%20.15X|\n", -100000);
	printf("11) Vrai PRINTF : |%15.20X|\n", -100000);
	printk(KERN_NORMAL,"11) Mon PRINTF  : |%15.20X|\n", -100000);
	printf("12) Vrai PRINTF : |%-10X|\n", 144);
	printk(KERN_NORMAL,"12) Mon PRINTF  : |%-10X|\n", 144);
	printf("13) Vrai PRINTF : |%-.10X|\n", 144);
	printk(KERN_NORMAL,"13) Mon PRINTF  : |%-.10X|\n", 144);
	printf("14) Vrai PRINTF : |%-20X|\n", -20000000);
	printk(KERN_NORMAL,"14) Mon PRINTF  : |%-20X|\n", -20000000);
	printf("15) Vrai PRINTF : |%08X|\n", 64);
	printk(KERN_NORMAL,"15) Mon PRINTF  : |%08X|\n", 64);
	printf("16) Vrai PRINTF : |%03.4X|\n", 10);
	printk(KERN_NORMAL,"16) Mon PRINTF  : |%03.4X|\n", 10);
	printf("17) Vrai PRINTF : |%#X|\n", 34);
	printk(KERN_NORMAL,"17) Mon PRINTF  : |%#X|\n", 34);
	printf("18) Vrai PRINTF : |%#.5X|\n", 34);
	printk(KERN_NORMAL,"18) Mon PRINTF  : |%#.5X|\n", 34);
	printf("19) Vrai PRINTF : |%#5X|\n", 86);
	printk(KERN_NORMAL,"19) Mon PRINTF  : |%#5X|\n", 86);
	printf("20) Vrai PRINTF : |%#10.5X|\n", 70);
	printk(KERN_NORMAL,"20) Mon PRINTF  : |%#10.5X|\n", 70);
	printf("21) Vrai PRINTF : |%#X|\n", 0);
	printk(KERN_NORMAL,"21) Vrai PRINTF : |%#X|\n", 0);
	printf("22) Vrai PRINTF : |%#.X|\n", 0);
	printk(KERN_NORMAL,"22) Mon PRINTF  : |%#.X|\n", 0);
	printf("23) Vrai PRINTF : |%.X|\n", 0);
	printk(KERN_NORMAL,"23) Mon PRINTF  : |%.X|\n", 0);
	printf("24) Vrai PRINTF : |%.X|\n", 88);
	printk(KERN_NORMAL,"24) Mon PRINTF  : |%.X|\n", 88);
	printf("25) Vrai PRINTF : |%#.X|\n", 88);
	printk(KERN_NORMAL,"25) Mon PRINTF  : |%#.X|\n", 88);
	printf("26) Vrai PRINTF : |%X|\n", UINT_MAX);
	printk(KERN_NORMAL,"26) Mon PRINT   : |%X|\n", UINT_MAX);
	printf("27) Vrai PRINTF : |%#X|\n", UINT_MAX);
	printk(KERN_NORMAL,"27) Mon PRINTF  : |%#X|\n", UINT_MAX);
	printk(KERN_NORMAL,"--------------------%%u--------------------\n");
	printf("01) Vrai PRINTF : |%u|\n", 34);
	printk(KERN_NORMAL,"01) Mon PRINTF  : |%u|\n", 34);
	printf("02) Vrai PRINTF : |%u|\n", -34);
	printk(KERN_NORMAL,"02) Mon PRINTF  : |%u|\n", -34);
	printf("03) Vrai PRINTF : |%-u|\n", 50);
	printk(KERN_NORMAL,"03) Mon PRINTF  : |%-u|\n", 50);
	printf("04) Vrai PRINTF : |%10u|\n", 90);
	printk(KERN_NORMAL,"04) Mon PRINTF  : |%10u|\n", 90);
	printf("05) Vrai PRINTF : |%.10u|\n", 90);
	printk(KERN_NORMAL,"05) Mon PRINTF  : |%.10u|\n", 90);
	printf("06) Vrai PRINTF : |%15u|\n", -100);
	printk(KERN_NORMAL,"06) Mon PRINTF  : |%15u|\n", -100);
	printf("07) Vrai PRINTF : |%.15u|\n", -100);
	printk(KERN_NORMAL,"07) Mon PRINTF  : |%.15u|\n", -100);
	printf("08) Vrai PRINTF : |%10.5u|\n", 52);
	printk(KERN_NORMAL,"08) Mon PRINTF  : |%10.5u|\n", 52);
	printf("09) Vrai PRINTF : |%5.10u|\n", 52);
	printk(KERN_NORMAL,"09) Mon PRINTF  : |%5.10u|\n", 52);
	printf("10) Vrai PRINTF : |%20.15u|\n", -100000);
	printk(KERN_NORMAL,"10) Mon PRINTF  : |%20.15u|\n", -100000);
	printf("11) Vrai PRINTF : |%15.20u|\n", -100000);
	printk(KERN_NORMAL,"11) Mon PRINTF  : |%15.20u|\n", -100000);
	printf("12) Vrai PRINTF : |%-10u|\n", 144);
	printk(KERN_NORMAL,"12) Mon PRINTF  : |%-10u|\n", 144);
	printf("13) Vrai PRINTF : |%-.10u|\n", 144);
	printk(KERN_NORMAL,"13) Mon PRINTF  : |%-.10u|\n", 144);
	printf("14) Vrai PRINTF : |%-20u|\n", -20000000);
	printk(KERN_NORMAL,"14) Mon PRINTF  : |%-20u|\n", -20000000);
	printf("15) Vrai PRINTF : |%08u|\n", 64);
	printk(KERN_NORMAL,"15) Mon PRINTF  : |%08u|\n", 64);
	printf("16) Vrai PRINTF : |%03.4u|\n", 10);
	printk(KERN_NORMAL,"16) Mon PRINTF  : |%03.4u|\n", 10);
	printf("17) Vrai PRINTF : |%.u|\n", 0);
	printk(KERN_NORMAL,"17) Mon PRINTF  : |%.u|\n", 0);
	printf("18) Vrai PRINTF : |%.u|\n", 88);
	printk(KERN_NORMAL,"18) Mon PRINTF  : |%.u|\n", 88);
	printf("19) Vrai PRINTF : |%u|\n", UINT_MAX);
	printk(KERN_NORMAL,"19) Mon PRINT   : |%u|\n", UINT_MAX);
	printf("--------------Basic test 42 fc--------------------\n");  		   
	printf("");
	printk(KERN_NORMAL,"");
	printf("\\n");
	printk(KERN_NORMAL,"\\n");
    printf("test\n");
	printk(KERN_NORMAL,"test\n");
    printf("test\\n");
	printk(KERN_NORMAL,"test\\n");
    printf("1234\n");
	printk(KERN_NORMAL,"1234\n");
    printf("%%\n");
	printk(KERN_NORMAL,"%%\n");
    printf("%5%\n");
	printk(KERN_NORMAL,"%5%\n");
    printf("%-5%\n");
	printk(KERN_NORMAL,"%-5%\n");
	printf("%.0%\n");
	printk(KERN_NORMAL,"%.0%\n");
	printf("%%\n", "test");
	printk(KERN_NORMAL,"%%\n", "test");
	printf("%   %\n", "test");
	printk(KERN_NORMAL,"%   %\n", "test");
	printf("%x\n", 42);
	printk(KERN_NORMAL,"%x\n", 42);
	printf("%X\n", 42);
	printk(KERN_NORMAL,"%X\n", 42);
	printf("%x\n", 0);
	printk(KERN_NORMAL,"%x\n", 0);
	printf("%X\n", 0);
	printk(KERN_NORMAL,"%X\n", 0);
	printf("%x\n", -42);
	printk(KERN_NORMAL,"%x\n", -42);
	printf("%X\n", -42);
	printk(KERN_NORMAL,"%X\n", -42);
	printf("%x\n", 4294967296);
	printk(KERN_NORMAL,"%x\n", 4294967296);
	printf("%X\n", 4294967296);
	printk(KERN_NORMAL,"%X\n", 4294967296);
	printf("%x\n", test1);
	printk(KERN_NORMAL,"%x\n", test1);
	printf("%10x\n", 42);
	printk(KERN_NORMAL,"%10x\n", 42);
  	printf("%-10x\n", 42);
	printk(KERN_NORMAL,"%-10x\n", 42);
  	printf("%lx\n", 4294967296);
	printk(KERN_NORMAL,"%lx\n", 4294967296);
  	printf("%llX\n", 4294967296);
	printk(KERN_NORMAL,"%llX\n", 4294967296);
  	printf("%hx\n", 4294967296);
	printk(KERN_NORMAL,"%hx\n", 4294967296);
	printf("%hhX\n", 4294967296);
  	printk(KERN_NORMAL,"%hhX\n", 4294967296);
	printf("%llx\n", 9223372036854775807);
	printk(KERN_NORMAL,"%llx\n", 9223372036854775807);
	printf("%llx\n", 9223372036854775808);
	printk(KERN_NORMAL,"%llx\n", 9223372036854775808);
	printf("%010x\n", 542);
	printk(KERN_NORMAL,"%010x\n", 542);
	printf("%-15x\n", 542);
	printk(KERN_NORMAL,"%-15x\n", 542);
	printf("%2x\n", 542);
	printk(KERN_NORMAL,"%2x\n", 542);
	printf("%.2x\n", 5427);
	printk(KERN_NORMAL,"%.2x\n", 5427);
	printf("%5.2x\n", 5427);
	printk(KERN_NORMAL,"%5.2x\n", 5427);
	printf("%#x\n", 42);
	printk(KERN_NORMAL,"%#x\n", 42);
	printf("%#llx\n", 9223372036854775807);   
	printk(KERN_NORMAL,"%#llx\n", 9223372036854775807);
	printf("%#x\n", 0);
	printk(KERN_NORMAL,"%#x\n", 0);
	printf("%#x\n", 42);
	printk(KERN_NORMAL,"%#x\n", 42);
	printf("%#X\n", 42);
	printk(KERN_NORMAL,"%#X\n", 42);
	printf("%#8x\n", 42);
	printk(KERN_NORMAL,"%#8x\n", 42);
	printf("%#08x\n", 42);
	printk(KERN_NORMAL,"%#08x\n", 42);
	printf("%#-08x\n", 42);
	printk(KERN_NORMAL,"%#-08x\n", 42);
	printf("@moulitest: %#.x %#.0x\n", 0, 0);
	printk(KERN_NORMAL,"@moulitest: %#.x %#.0x\n", 0, 0);
	printf("@moulitest: %.x %.0x\n", 0, 0);
	printk(KERN_NORMAL,"@moulitest: %.x %.0x\n", 0, 0);
	printf("@moulitest: %5.x %5.0x\n", 0, 0);
	printk(KERN_NORMAL,"@moulitest: %5.x %5.0x\n", 0, 0);
	printf("%s\n", "abc");
	printk(KERN_NORMAL,"%s\n", "abc");
	printf("%s\n", "this is a string");
	printk(KERN_NORMAL,"%s\n", "this is a string");
	printf("%s \n", "this is a string");
	printk(KERN_NORMAL,"%s \n", "this is a string");
	printf("%s  \n", "this is a string");
	printk(KERN_NORMAL,"%s  \n", "this is a string");
	printf("this is a %s\n", "string");
	printk(KERN_NORMAL,"this is a %s\n", "string");
	printf("this is a %s\n", "string");
	printk(KERN_NORMAL,"%s is a string\n", "this");
	printf("Line Feed %s\n", "\\n");
	printk(KERN_NORMAL,"Line Feed %s\n", "\\n");
	printf("%10s is a string\n", "this");
	printk(KERN_NORMAL,"%10s is a string\n", "this");
	printf("%.2s is a string\n", "this");
	printk(KERN_NORMAL,"%.2s is a string\n", "this");
	printf("%5.2s is a string\n", "this");
	printk(KERN_NORMAL,"%5.2s is a string\n", "this");
	printf("%10s is a string\n", "");
	printk(KERN_NORMAL,"%10s is a string\n", "");
	printf("%.2s is a string\n", "");
	printk(KERN_NORMAL,"%.2s is a string\n", "");
	printf("%5.2s is a string\n", "");
	printk(KERN_NORMAL,"%5.2s is a string\n", "");
	printf("%-10s is a string\n", "this");
	printk(KERN_NORMAL,"%-10s is a string\n", "this");
	printf("%-.2s is a string\n", "this");
	printk(KERN_NORMAL,"%-.2s is a string\n", "this");
	printf("%-5.2s is a string\n", "this");
	printk(KERN_NORMAL,"%-5.2s is a string\n", "this");
	printf("%-10s is a string\n", "");
	printk(KERN_NORMAL,"%-10s is a string\n", "");
	printf("%-.2s is a string\n", "");
	printk(KERN_NORMAL,"%-.2s is a string\n", "");
	printf("%-5.2s is a string\n", "");
	printk(KERN_NORMAL,"%-5.2s is a string\n", "");
	printf("%s %s\n", "this", "is");
	printk(KERN_NORMAL,"%s %s\n", "this", "is");
	printf("%s %s %s\n", "this", "is", "a");
	printk(KERN_NORMAL,"%s %s %s\n", "this", "is", "a");
	printf("%s %s %s %s\n", "this", "is", "a", "multi");
	printk(KERN_NORMAL,"%s %s %s %s\n", "this", "is", "a", "multi");
	printf("%s %s %s %s string. gg!\n", "this", "is", "a", "multi", "string");
	printk(KERN_NORMAL,"%s %s %s %s string. gg!\n", "this", "is", "a", "multi", "string");
	printf("%s%s%s%s%s\n", "this", "is", "a", "multi", "string");
	printk(KERN_NORMAL,"%s%s%s%s%s\n", "this", "is", "a", "multi", "string");
	printf("@moulitest: %s\n", NULL);
	printk(KERN_NORMAL,"@moulitest: %s\n", NULL);
	printf("%.2c\n", NULL);
	printk(KERN_NORMAL,"%.2c\n", NULL);
	printf("%s %s\n", NULL, "string");
	printk(KERN_NORMAL,"%s %s\n", NULL, "string");
	printf("%c\n", 42);
	printk(KERN_NORMAL,"%c\n", 42);
	printf("%5c\n", 42);
	printk(KERN_NORMAL,"%5c\n", 42);
	printf("%-5c\n", 42);
	printk(KERN_NORMAL,"%-5c\n", 42);
	printf("@moulitest: %c\n", 0);
	printk(KERN_NORMAL,"@moulitest: %c\n", 0);
	printf("%2c\n", 0);
	printk(KERN_NORMAL,"%2c\n", 0);
	printf("null %c and text\n", 0);
	printk(KERN_NORMAL,"null %c and text\n", 0);
	printf("% c\n", 0);
	printk(KERN_NORMAL,"% c\n", 0);
	printf("%o\n", 40);
	printk(KERN_NORMAL,"%o\n", 40);
	printf("%5o\n", 41);
	printk(KERN_NORMAL,"%5o\n", 41);
	printf("%05o\n", 42);
	printk(KERN_NORMAL,"%05o\n", 42);
	printf("%-5o\n", 2500);
	printk(KERN_NORMAL,"%-5o\n", 2500);
	printf("%#6o\n", 2500);
	printk(KERN_NORMAL,"%#6o\n", 2500);
	printf("%-#6o\n", 2500);
	printk(KERN_NORMAL,"%-#6o\n", 2500);
	printf("%-05o\n", 2500);
	printk(KERN_NORMAL,"%-05o\n", 2500);
	printf("%-5.10o\n", 2500);
	printk(KERN_NORMAL,"%-5.10o\n", 2500);
	printf("%-10.5o\n", 2500);
	printk(KERN_NORMAL,"%-10.5o\n", 2500);
	printf("@moulitest: %o\n", 0);
	printk(KERN_NORMAL,"@moulitest: %o\n", 0);
	printf("@moulitest: %.o %.0o\n", 0, 0);
	printk(KERN_NORMAL,"@moulitest: %.o %.0o\n", 0, 0);
	printf("@moulitest: %5.o %5.0o\n", 0, 0);
	printk(KERN_NORMAL,"@moulitest: %5.o %5.0o\n", 0, 0);
	printf("@moulitest: %#.o %#.0o\n", 0, 0);
	printk(KERN_NORMAL,"@moulitest: %#.o %#.0o\n", 0, 0);
	printf("@moulitest: %.10o\n", 42);
	printk(KERN_NORMAL,"@moulitest: %.10o\n", 42);
	printf("%d\n", 1);
	printk(KERN_NORMAL,"%d\n", 1);
	printf("the %d\n", 1);
	printk(KERN_NORMAL,"the %d\n", 1);
	printf("%d is one\n", 1);
	printk(KERN_NORMAL,"%d is one\n", 1);
	printf("%d\n", -1);
	printk(KERN_NORMAL,"%d\n", -1);
	printf("%d\n", 4242);
	printk(KERN_NORMAL,"%d\n", 4242);
	printf("%d\n", -4242);
	printk(KERN_NORMAL,"%d\n", -4242);
	printf("%d\n", 2147483647);
	printk(KERN_NORMAL,"%d\n", 2147483647);
	printf("%d\n", 2147483648);
	printk(KERN_NORMAL,"%d\n", 2147483648);
	printf("%d\n", -2147483648);
	printk(KERN_NORMAL,"%d\n", -2147483648);
	printf("%d\n", -2147483649);
	printk(KERN_NORMAL,"%d\n", -2147483649);
	printf("% d\n", 42);
	printk(KERN_NORMAL,"% d\n", 42);
	printf("% d\n", -42);
	printk(KERN_NORMAL,"% d\n", -42);
	printf("%+d\n", 42);
	printk(KERN_NORMAL,"%+d\n", 42);
	printf("%+d\n", -42);
	printk(KERN_NORMAL,"%+d\n", -42);
	printf("%+d\n", 0);
	printk(KERN_NORMAL,"%+d\n", 0);
	//printf("%+d", 4242424242424242424242);
	//printk(KERN_NORMAL,"%+d", 4242424242424242424242);
	printf("% +d\n", 42);
	printk(KERN_NORMAL,"% +d\n", 42);
	printf("% +d\n", -42);
	printk(KERN_NORMAL,"% +d\n", -42);
	printf("%+ d\n", 42);
	printk(KERN_NORMAL,"%+ d\n", 42);
	printf("%+ d\n", -42);
	printk(KERN_NORMAL,"%+ d\n", -42);
	printf("%  +d\n", 42);
	printk(KERN_NORMAL,"%  +d\n", 42);
	printf("%  +d\n", -42);
	printk(KERN_NORMAL,"%  +d\n", -42);
	printf("%+  d\n", 42);
	printk(KERN_NORMAL,"%+  d\n", 42);
	printf("%+  d\n", -42);
	printk(KERN_NORMAL,"%+  d\n", -42);
	printf("% ++d\n", 42);
	printk(KERN_NORMAL,"% ++d\n", 42);
	printf("% ++d\n", -42);
	printk(KERN_NORMAL,"% ++d\n", -42);
	printf("%++ d\n", 42);
	printk(KERN_NORMAL,"%++ d\n", 42);
	printf("%++ d\n", -42);
	printk(KERN_NORMAL,"%++ d\n", -42);
	printf("%0d\n", -42);
	printk(KERN_NORMAL,"%0d\n", -42);
	printf("%00d\n", -42);
	printk(KERN_NORMAL,"%00d\n", -42);
	printf("%5d\n", 42);
	printk(KERN_NORMAL,"%5d\n", 42);
	printf("%05d\n", 42);
	printk(KERN_NORMAL,"%05d\n", 42);
	printf("%0+5d\n", 42);
	printk(KERN_NORMAL,"%0+5d\n", 42);
	printf("%5d\n", -42);
	printk(KERN_NORMAL,"%5d\n", -42);
	printf("%05d\n", -42);
	printk(KERN_NORMAL,"%05d\n", -42);
	printf("%0+5d\n", -42);
	printk(KERN_NORMAL,"%0+5d\n", -42);
	printf("%-5d\n", 42);
	printk(KERN_NORMAL,"%-5d\n", 42);
	printf("%-05d\n", 42);
	printk(KERN_NORMAL,"%-05d\n", 42);
	printf("%-5d\n", -42);
	printk(KERN_NORMAL,"%-5d\n", -42);
	printf("%-05d\n", -42);
	printk(KERN_NORMAL,"%-05d\n", -42);
	printf("%hd\n", 32767);
	printk(KERN_NORMAL,"%hd\n", 32767);
	printf("%hd\n", -32768);
	printk(KERN_NORMAL,"%hd\n", -32768);
	printf("%hd\n", 32768);
	printk(KERN_NORMAL,"%hd\n", 32768);
	printf("%hd\n", -32769);
	printk(KERN_NORMAL,"%hd\n", -32769);
	printf("%hhd\n", 127);
	printk(KERN_NORMAL,"%hhd\n", 127);
	printf("%hhd\n", 128);
	printk(KERN_NORMAL,"%hhd\n", 128);
	printf("%hhd\n", -128);
	printk(KERN_NORMAL,"%hhd\n", -128);
	printf("%hhd\n", -129);
	printk(KERN_NORMAL,"%hhd\n", -129);
	printf("%ld\n", 2147483647);
	printk(KERN_NORMAL,"%ld\n", 2147483647);
	printf("%ld\n", -2147483648);
	printk(KERN_NORMAL,"%ld\n", -2147483648);
	printf("%ld\n", 2147483648);
	printk(KERN_NORMAL,"%ld\n", 2147483648);
	printf("%ld\n", -2147483649);
	printk(KERN_NORMAL,"%ld\n", -2147483649);
	printf("%lld\n", 9223372036854775807);
	printk(KERN_NORMAL,"%lld\n", 9223372036854775807);
	printf("%lld\n", -9223372036854775808);
	printk(KERN_NORMAL,"%lld\n", -9223372036854775808);
	printf("%d\n", 1);
	printk(KERN_NORMAL,"%d\n", 1);
	printf("%d %d\n", 1, -2);
	printk(KERN_NORMAL,"%d %d\n", 1, -2);
	printf("%d %d %d\n", 1, -2, 33);
	printk(KERN_NORMAL,"%d %d %d\n", 1, -2, 33);
	printf("%d %d %d %d\n", 1, -2, 33, 42);
	printk(KERN_NORMAL,"%d %d %d %d\n", 1, -2, 33, 42);
	printf("%d %d %d %d gg!\n", 1, -2, 33, 42, 0);
	printk(KERN_NORMAL,"%d %d %d %d gg!\n", 1, -2, 33, 42, 0);
	printf("%4.15d\n", 42);
	printk(KERN_NORMAL,"%4.15d\n", 42);
	printf("%.2d\n", 4242);
	printk(KERN_NORMAL,"%.2d\n", 4242);
	printf("%.10d\n", 4242);
	printk(KERN_NORMAL,"%.10d\n", 4242);
	printf("%10.5d\n", 4242);
	printk(KERN_NORMAL,"%10.5d\n", 4242);
	printf("%-10.5d\n", 4242);
	printk(KERN_NORMAL,"%-10.5d\n", 4242);
	printf("% 10.5d\n", 4242);
	printk(KERN_NORMAL,"% 10.5d\n", 4242);
	printf("%+10.5d\n", 4242);
	printk(KERN_NORMAL,"%+10.5d\n", 4242);
	printf("%-+10.5d\n", 4242);
	printk(KERN_NORMAL,"%-+10.5d\n", 4242);
	printf("%03.2d\n", 0);
	printk(KERN_NORMAL,"%03.2d\n", 0);
	printf("%03.2d\n", 1);
	printk(KERN_NORMAL,"%03.2d\n", 1);
	printf("%03.2d\n", -1);
	printk(KERN_NORMAL,"%03.2d\n", -1);
	printf("@moulitest: %.10d\n", -42);
	printk(KERN_NORMAL,"@moulitest: %.10d\n", -42);
	printf("@moulitest: %.d %.0d\n", 42, 43);
	printk(KERN_NORMAL,"@moulitest: %.d %.0d\n", 42, 43);
	printf("@moulitest: %.d %.0d\n", 0, 0);
	printk(KERN_NORMAL,"@moulitest: %.d %.0d\n", 0, 0);
	printf("@moulitest: %5.d %5.0d\n", 0, 0);
	printk(KERN_NORMAL,"@moulitest: %5.d %5.0d\n", 0, 0);
	printf("%u\n", 0);
	printk(KERN_NORMAL,"%u\n", 0);
	printf("%u\n", 1);
	printk(KERN_NORMAL,"%u\n", 1);
	printk(KERN_NORMAL,"%u\n", -1);
	printk(KERN_NORMAL,"%u\n", -1);
	printf("%u\n", 4294967295);
	printk(KERN_NORMAL,"%u\n", 4294967295);
	printf("%u\n", 4294967296);
	printk(KERN_NORMAL,"%u\n", 4294967296);
	printf("%5u\n", 4294967295);
	printk(KERN_NORMAL,"%5u\n", 4294967295);
	printf("%15u\n", 4294967295);
	printk(KERN_NORMAL,"%15u\n", 4294967295);
	printf("%-15u\n", 4294967295);
	printk(KERN_NORMAL,"%-15u\n", 4294967295);
	printf("%015u\n", 4294967295);
	printk(KERN_NORMAL,"%015u\n", 4294967295);
	printf("% u\n", 4294967295);
	printk(KERN_NORMAL,"% u\n", 4294967295);
	printf("%+u\n", 4294967295);
	printk(KERN_NORMAL,"%+u\n", 4294967295);
	printf("%lu\n", 4294967295);
	printk(KERN_NORMAL,"%lu\n", 4294967295);
	printf("%lu\n", 4294967296);
	printk(KERN_NORMAL,"%lu\n", 4294967296);
	printk(KERN_NORMAL,"%lu\n", -42);
	printk(KERN_NORMAL,"%lu\n", -42);
	printf("%llu\n", 4999999999);
	printk(KERN_NORMAL,"%llu\n", 4999999999);
	printf("@moulitest: %.5u\n", 42);
	printk(KERN_NORMAL,"@moulitest: %.5u\n", 42);
	printf("--------------------Leaks 42fc---------------");
	printk(KERN_NORMAL,"%jd\\n\n", 9223372036854775807);
    printk(KERN_NORMAL,"%zd\\n\n", 4294967295);
    printk(KERN_NORMAL,"%\\n\n");
    printk(KERN_NORMAL,"%U\\n\n", 4294967295);
    printk(KERN_NORMAL,"%S\\n\n", L"ݗݜशব");
    printk(KERN_NORMAL,"%C\\n\n", 15000);
    printk(KERN_NORMAL,"%-05d\n", -42);
    printk(KERN_NORMAL,"%p\\n\n", &printk);
}
